name: scheduler
description: O app para realizar o agendamento de suas atividades diárias! 
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  http: ^1.1.0
  shared_preferences: ^2.0.6

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  flutter_native_splash: ^2.3.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0
  dio: ^5.4.3+1
  jwt_decoder: ^2.0.1
  loading_animation_widget: ^1.2.1
  flutter_animate: ^4.5.0
  internet_connection_checker_plus: ^2.4.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  dio_smart_retry: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: assets/icons/background.png
  adaptive_icon_foreground: assets/icons/calendar.png
  adaptive_icon_padding: true

flutter_native_splash:
  android: true
  ios: true
  color: "#03A9F4"
  image: assets/icons/calendar.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/relaxed.jpg
    - assets/icons/icon.png
    - assets/images/flutter_framework.jpg
    - assets/images/quarkus.jpg
    - assets/images/creator.png
    - assets/icons/calendar.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
